server:
  port: 8081
  #port: 0     # let springboot choose random port to run on

spring:
  application:
    name: demo-service

# Option 1 *** NONE OF BELOW OPTION WORKED FOR ME ***
#  cloud:
#    loadbalancer:
#      ribbon:
#        enable: false
# And... inform the "url" attribute at FeignClient --> @FeignClient(name = "service1", url = "localhost:8082")

# Option 2
#  cloud:
#    loadbalancer:
#      ribbon:
#        enable: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
    #name   #this is from feign client for DemoServiceClient (${feign.name})

